=== AMWA-TV/is-05/v1.0.0/schemas/resolved/v1.0-sender-response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a sender",
  "title": "Sender resource",
  "additionalProperties": false,
  "required": [
    "receiver_id",
    "master_enable",
    "activation",
    "transport_params"
  ],
  "properties": {
    "receiver_id": {
      "description": "ID of the target Receiver of this Sender. This will be null if the sender is operating in multicast mode, or has not been assigned a receiver in unicast mode, or is sending to a non-NMOS receiver in unicast mode.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "default": null
    },
    "master_enable": {
      "description": "Master on/off control for receiver",
      "type": "boolean",
      "default": true
    },
    "activation": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Parameters concerned with activation of the transport parameters",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "mode",
        "requested_time",
        "activation_time"
      ],
      "properties": {
        "mode": {
          "description": "Mode of activation: immediate (on message receipt), scheduled_absolute (when internal clock >= requested_time), scheduled_relative (when internal clock >= time of message receipt + requested_time), or null (no activation scheduled). This parameter returns to null on the staged endpoint once an activation is completed. For immediate activations, in the response to the PATCH request this field will be set to 'activate_immediate', but will be null in response to any subsequent GET requests.",
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "activate_immediate",
                "activate_scheduled_absolute",
                "activate_scheduled_relative"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "requested_time": {
          "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating time (absolute or relative) for activation requested. This field returns to null once the activation is completed on the staged endpoint. For an immediate activation this field will always be null on the staged endpoint, even in the response to the PATCH request.",
          "anyOf": [
            {
              "type": "string",
              "pattern": "^[0-9]+:[0-9]+$"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "activation_time": {
          "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating the absolute time the receiver will or did actually activate for scheduled activations, or the time activation occurred for immediate activations. On the staged endpoint this field returns to null once the activation is completed. For immediate activations on the staged endpoint this property will be the time the activation actually occurred in the response to the PATCH request, but null in response to any GET requests thereafter.",
          "anyOf": [
            {
              "type": "string",
              "pattern": "^[0-9]+:[0-9]+$"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      }
    },
    "transport_params": {
      "description": "Transport-specific parameters",
      "oneOf": [
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "description": "Describes RTP Sender transport parameters. The constraints in this schema are minimum constraints, but may be further constrained at the constraints endpoint. As a minimum all senders must support `source_ip`, `destination_ip`, `source_port`, `rtp_enabled` and `destination_port`. Senders supporting FEC and/or RTCP must support parameters prefixed with `fec` and `rtcp` respectively.",
          "title": "RTP Sender Transport Parameters",
          "type": "array",
          "items": {
            "type": "object",
            "title": "Sender Output",
            "properties": {
              "source_ip": {
                "type": "string",
                "description": "IP address from which RTP packets will be sent (IP address of interface bound to this output). The sender should provide an enum in the constraints endpoint, which should contain 'auto', and the available interface addresses. If the parameter is set to auto the sender should establish for itself which interface it should use, based on routing rules or its own internal configuration.",
                "anyOf": [
                  {
                    "format": "ipv4"
                  },
                  {
                    "format": "ipv6"
                  },
                  {
                    "pattern": "^auto$"
                  }
                ],
                "default": "auto"
              },
              "destination_ip": {
                "type": "string",
                "description": "IP address to which RTP packets will be sent. If auto is set the sender should select a multicast address to send to itself. For example it may implement MADCAP (RFC 2730), ZMAAP, or be allocated address by some other system responsible for co-ordination multicast address use.",
                "anyOf": [
                  {
                    "format": "ipv4"
                  },
                  {
                    "format": "ipv6"
                  },
                  {
                    "pattern": "^auto$"
                  }
                ]
              },
              "source_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "source port for RTP packets (auto = 5004)",
                "minimum": 0,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "destination_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "destination port for RTP packets (auto = 5004)",
                "minimum": 1,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "fec_enabled": {
                "type": "boolean",
                "description": "FEC on/off",
                "default": false
              },
              "fec_destination_ip": {
                "type": "string",
                "description": "May be used if NAT is being used at the destination (auto = destination_ip)",
                "anyOf": [
                  {
                    "format": "ipv4"
                  },
                  {
                    "format": "ipv6"
                  },
                  {
                    "pattern": "^auto$"
                  }
                ],
                "default": "auto"
              },
              "fec_type": {
                "type": "string",
                "description": "forward error correction mode to apply",
                "enum": [
                  "XOR",
                  "Reed-Solomon"
                ],
                "default": "XOR"
              },
              "fec_mode": {
                "type": "string",
                "description": "forward error correction mode to apply",
                "enum": [
                  "1D",
                  "2D"
                ],
                "default": "1D"
              },
              "fec_block_width": {
                "type": "integer",
                "description": "width of block over which FEC is calculated in packets",
                "minimum": 4,
                "maximum": 200,
                "default": 4
              },
              "fec_block_height": {
                "type": "integer",
                "description": "height of block over which FEC is calculated in packets",
                "minimum": 4,
                "maximum": 200,
                "default": 4
              },
              "fec1D_destination_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "destination port for RTP Column FEC packets (auto = RTP destination_port + 2)",
                "minimum": 1,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "fec2D_destination_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "destination port for RTP Row FEC packets (auto = RTP destination_port + 4)",
                "minimum": 1,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "fec1D_source_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "source port for RTP FEC packets (auto = RTP source_port + 2)",
                "minimum": 0,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "fec2D_source_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "source port for RTP FEC packets (auto = RTP source_port + 4)",
                "minimum": 0,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "rtcp_enabled": {
                "type": "boolean",
                "description": "rtcp on/off",
                "default": false
              },
              "rtcp_destination_ip": {
                "type": "string",
                "description": "IP address to which RTCP packets will be sent (auto = same as RTP destination_ip)",
                "anyOf": [
                  {
                    "format": "ipv4"
                  },
                  {
                    "format": "ipv6"
                  },
                  {
                    "pattern": "^auto$"
                  }
                ],
                "default": "auto"
              },
              "rtcp_destination_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "destination port for RTCP packets (auto = next highest odd port number after RTP destination_port)",
                "minimum": 1,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "rtcp_source_port": {
                "type": [
                  "integer",
                  "string"
                ],
                "description": "source port for RTCP packets (destination port for RTCP packets (auto = RTP destination_port + 1))",
                "minimum": 0,
                "maximum": 65535,
                "pattern": "^auto$",
                "default": "auto"
              },
              "rtp_enabled": {
                "type": "boolean",
                "description": "RTP transmission active/inactive",
                "default": true
              }
            }
          }
        },
        {
          "not": {}
        }
      ]
    }
  }
}

=== AMWA-TV/is-05/examples/sender-get-200-uninit.json
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_params": [{
    "source_ip": "auto",
    "destination_ip": "auto",
    "source_port": "auto",
    "destination_port": "auto",
    "fec_enabled": false,
    "fec_destination_ip": "auto",
    "fec_type": "XOR",
    "fec_mode": "1D",
    "fec_block_width": 4,
    "fec_block_height": 4,
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "fec1D_source_port": "auto",
    "fec2D_source_port": "auto",
    "rtcp_enabled": false,
    "rtcp_destination_ip": "auto",
    "rtcp_destination_port": "auto",
    "rtcp_source_port": "auto",
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/branches/master/examples/v1.0-stage-relative-success.json
{
    "master_enable": true,
    "receiver_id": "0a174530-e3cf-11e6-bf01-fe55135034f3",
    "activation": {
        "mode": "activate_scheduled_relative",
        "requested_time": "2:0",
        "activation_time": "1496759200:0"
    },
    "transport_params": [{
        "source_ip": "172.29.82.23",
        "destination_ip": "172.29.82.95",
        "source_port": 5000,
        "destination_port": 5000,
        "fec_enabled": true,
        "fec_type": "XOR",
        "fec_mode": "2D",
        "fec_block_width": 50,
        "fec_block_height": 50,
        "fec1D_destination_port": "auto",
        "fec2D_destination_port": "auto",
        "fec1D_source_port": 5010,
        "fec2D_source_port": 5012,
        "rtcp_enabled": true,
        "rtcp_destination_ip": "172.29.82.24",
        "rtcp_destination_port": 5008,
        "rtcp_source_port": 5008,
        "rtp_enabled": true
    }, {
        "source_ip": "172.30.82.23",
        "destination_ip": "172.30.82.95",
        "source_port": 5000,
        "destination_port": 5000,
        "fec_enabled": true,
        "fec_type": "XOR",
        "fec_mode": "2D",
        "fec_block_width": 50,
        "fec_block_height": 50,
        "fec1D_destination_port": "auto",
        "fec2D_destination_port": "auto",
        "fec1D_source_port": 5010,
        "fec2D_source_port": 5012,
        "rtcp_enabled": true,
        "rtcp_destination_ip": "172.30.82.24",
        "rtcp_destination_port": 5008,
        "rtcp_source_port": 5008,
        "rtp_enabled": true
    }]
}

=== AMWA-TV/is-05/examples/sender-active-get.json
{
  "receiver_id": "0a174530-e3cf-11e6-bf01-fe55135034f3",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": "1496759200:0",
    "activation_time": "1496759200:0"
  },
  "transport_params": [{
    "source_ip": "172.29.82.23",
    "destination_ip": "172.29.82.95",
    "source_port": 5000,
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_destination_ip": "172.29.82.95",
    "fec_type": "XOR",
    "fec_mode": "2D",
    "fec_block_width": 50,
    "fec_block_height": 50,
    "fec1D_destination_port": 5002,
    "fec2D_destination_port": 5004,
    "fec1D_source_port": 5002,
    "fec2D_source_port": 5004,
    "rtcp_enabled": true,
    "rtcp_destination_ip": "172.29.82.24",
    "rtcp_destination_port": 5008,
    "rtcp_source_port": 5008,
    "rtp_enabled": true
  }, {
    "source_ip": "172.30.82.23",
    "destination_ip": "172.30.82.95",
    "source_port": 5000,
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_destination_ip": "172.30.82.95",
    "fec_type": "XOR",
    "fec_mode": "2D",
    "fec_block_width": 50,
    "fec_block_height": 50,
    "fec1D_destination_port": 5002,
    "fec2D_destination_port": 5004,
    "fec1D_source_port": 5002,
    "fec2D_source_port": 5004,
    "rtcp_enabled": true,
    "rtcp_destination_ip": "172.30.82.24",
    "rtcp_destination_port": 5008,
    "rtcp_source_port": 5008,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/v1.0-sender-stage-success-redundant-streams.json
{
  "master_enable": true,
  "receiver_id": null,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null,
    "activation_time": null
  },
  "transport_params": [{
    "source_ip": "192.168.200.10",
    "destination_ip": "232.105.26.177",
    "source_port": 5000,
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_type": "XOR",
    "fec_mode": "2D",
    "fec_block_width": 50,
    "fec_block_height": 50,
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "fec1D_source_port": 5010,
    "fec2D_source_port": 5012,
    "rtcp_enabled": true,
    "rtcp_destination_ip": "232.22.4.59",
    "rtcp_destination_port": 5008,
    "rtcp_source_port": 5008,
    "rtp_enabled": true
  }, {
    "source_ip": "192.168.210.10",
    "destination_ip": "232.3.28.144",
    "source_port": 5000,
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_type": "XOR",
    "fec_mode": "2D",
    "fec_block_width": 50,
    "fec_block_height": 50,
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "fec1D_source_port": 5010,
    "fec2D_source_port": 5012,
    "rtcp_enabled": true,
    "rtcp_destination_ip": "232.79.192.98",
    "rtcp_destination_port": 5008,
    "rtcp_source_port": 5008,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/v1.0-sender-active-get-uninit.json
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_params": [{
    "source_ip": "172.29.82.23",
    "destination_ip": "232.21.98.4",
    "source_port": 5004,
    "destination_port": 5004,
    "fec_enabled": false,
    "fec_destination_ip": "172.29.82.23",
    "fec_type": "XOR",
    "fec_mode": "1D",
    "fec_block_width": 4,
    "fec_block_height": 4,
    "fec1D_destination_port": 5006,
    "fec2D_destination_port": 5008,
    "fec1D_source_port": 5006,
    "fec2D_source_port": 5008,
    "rtcp_enabled": false,
    "rtcp_destination_ip": "172.29.82.23",
    "rtcp_destination_port": 5005,
    "rtcp_source_port": 5005,
    "rtp_enabled": false
  }]
}

=== AMWA-TV/is-05/examples/sender-active-get-mqtt.json
{
  "receiver_id": "69744dfb-0557-4202-b1f1-4d1a741ee2bb",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": "1541508905:0",
    "activation_time": "1541508905:0"
  },
  "transport_params": [{
    "destination_host": "broker.mydomain.com",
    "destination_port": 1883,
    "broker_topic": "my_topic_name",
    "broker_protocol": "mqtt",
    "broker_authorization": false,
    "connection_status_broker_topic": "my_status_topic_name"
  }]
}
