=== AMWA-TV/is-05/APIs/schemas/v1.0-receiver-stage-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a receiver",
  "title": "Receiver resource",
  "additionalProperties": false,
  "properties": {
    "sender_id": {
      "description": "ID of the Sender subscribed to by this Receiver. This will be null if the receiver has not been configured to receive anything, or if it is receiving from a non-NMOS sender.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "master_enable": {
      "description": "Master on/off control for receiver",
      "type": "boolean",
      "default": true
    },
    "activation": {
      "description": "Parameters concerned with activation of the transport parameters",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "mode": {
          "description": "Mode of activation: immediate (on message receipt), scheduled_absolute (when internal clock >= requested_time), scheduled_relative (when internal clock >= time of message receipt + requested_time), or null (no activation scheduled)",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "activate_immediate",
            "activate_scheduled_absolute",
            "activate_scheduled_relative",
            null
          ]
        },
        "requested_time": {
          "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating time (absolute or relative) for activation",
          "type": [
              "string",
              "null"
            ],
          "pattern": "^[0-9]+:[0-9]+$"
        }
      }
    },
    "transport_file": {
      "type": "object",
      "description": "Transport file parameters",
      "additionalProperties": false,
      "properties": {
        "data": {
          "description": "Content of the transport file",
          "type": [
              "string",
              "null"
          ]
        },
        "type": {
          "description": "IANA assigned media type for file (e.g application/sdp)",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "transport_params": {
      "description": "Transport-specific parameters",
      "oneOf": [
        { "$ref": "v1.0_receiver_transport_params_rtp.json" },
        { "$ref": "v1.0_receiver_transport_params_dash.json" }
      ]
    }
  }
}

=== AMWA-TV/is-05/examples/v1.0-receiver-patch-redundant-streams.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
      "interface_ip": "192.168.200.15",
      "multicast_ip": "232.105.26.177",
      "source_ip": "192.168.200.10",
      "destination_port": 5000,
      "rtp_enabled": true
    },
    {
      "interface_ip": "192.168.210.15",
      "multicast_ip": "232.3.28.144",
      "source_ip": "192.168.210.10",
      "destination_port": 5000,
      "rtp_enabled": true
    }
  ]
}

=== AMWA-TV/is-05/branches/master/examples/v1.0-receiver-patch-absolute.json
{
    "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
    "master_enable": true,
    "activation": {
        "mode": "activate_scheduled_absolute",
        "requested_time": "1496677550:20"
    },
    "transport_params": [{
        "source_ip": "172.23.19.49"
    }, {
        "source_ip": "172.23.19.49"
    }]
}

=== AMWA-TV/is-05/examples/v1.0-receiver-patch-unicast.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
    "interface_ip": "192.168.200.15",
    "multicast_ip": null,
    "source_ip": "192.168.200.10",
    "destination_port": 5000,
    "rtp_enabled": true
  }]
}
